/*
 * generated by Xtext
 */
package com.devfactory.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class KeyStoneUiModule extends com.devfactory.ui.AbstractKeyStoneUiModule {
	public KeyStoneUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
