/*
 * generated by Xtext
 */
package com.devfactory;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KeyStoneRuntimeModule extends com.devfactory.AbstractKeyStoneRuntimeModule {

}
