/*
* generated by Xtext
*/
package com.devfactory;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class KeyStoneStandaloneSetup extends KeyStoneStandaloneSetupGenerated{

	public static void doSetup() {
		new KeyStoneStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

